import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Layout/Navbar";
import { Toaster } from "react-hot-toast";
import { Footer } from "@/components";
import CartContextProvider from "@/Contexts/cartContext";
import { WishlistProvider } from "@/Contexts/wishlistContext";
import ProvidersContainer from "@/components/ProvidersContauner/ProvidersContainer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ProvidersContainer>
          <CartContextProvider>
            <WishlistProvider>
              <Navbar />
              {children}
              <Footer />
              <Toaster position="top-right" />
            </WishlistProvider>
          </CartContextProvider>
        </ProvidersContainer>
      </body>
    </html>
  );
}
